#!/bin/bash

gem install rails --version=2.1.1 --verbose --no-rdoc --no-ri --conservative
gem install mysql --verbose --no-rdoc --no-ri --conservative
gem install mysql2 --version=0.2.18 --verbose --no-rdoc --no-ri --conservative
gem install test-unit --verbose --no-rdoc --no-ri --conservative
gem install RedCloth --verbose --no-rdoc --no-ri --conservative
gem install sparql --verbose --no-rdoc --no-ri --conservative
cd /vagrant
if [ -d mushroom-observer ];
	then
		cd mushroom-observer; git pull
	else
		git clone https://github.com/MushroomObserver/mushroom-observer.git
		cd mushroom-observer
fi
mysql -u root -proot < db/initialize.sql
mysql -u mo -pmo mo_development < /vagrant/init.sql
rake db:migrate
rake lang:update
# script/run_tests
chown -R vagrant:vagrant /var/web/mushroom-observer
