#!/bin/bash

dir=$PWD
gem install rails --version=2.1.1 --verbose --no-rdoc --no-ri --conservative
gem install mysql --verbose --no-rdoc --no-ri --conservative
gem install mysql2 --version=0.2.18 --verbose --no-rdoc --no-ri --conservative
gem install test-unit --verbose --no-rdoc --no-ri --conservative
gem install RedCloth --verbose --no-rdoc --no-ri --conservative
gem install sparql --verbose --no-rdoc --no-ri --conservative
cd /vagrant
if [ -d mushroom-observer ];
	then
		cd mushroom-observer; git pull
	else
		git clone https://github.com/MushroomObserver/mushroom-observer.git
		cd mushroom-observer
fi
cp $dir/config-script/database.yml config
apt-get install -y -q imagemagick libmagickcore-dev libmagickwand-dev libjpeg-dev libjpeg-progs
gem install rmagick --verbose --no-rdoc --no-ri --conservative
if [ -f /usr/local/sbin/jpegresize ];
	then
		gcc script/jpegresize.c -ljpeg -lm -O2 -o /usr/local/sbin/jpegresize
fi
if [ -f /usr/local/sbin/jpegexiforient ];
	then
	  gcc script/jpegexiforient.c -o /usr/local/sbin/jpegexiforient
fi
if [ -f /usr/local/sbin/exifautotran ];
	then
    cp script/exifautotran.sh /usr/local/sbin/exifautotran; chmod 755 /usr/local/sbin/exifautotran
fi

mysql -u root -proot < db/initialize.sql
mysql -u mo -pmo mo_development < $dir/config-script/init.sql
rake db:migrate
rake lang:update
chown -R vagrant:vagrant /vagrant/mushroom-observer
